version: "3"

services:
  vectrum_node:
    image: vectrum/vectrum:latest
    command: /opt/vectrum/bin/vectrum-node.sh --data-dir /data -e --http-alias=vectrum_node:8888 --http-alias=127.0.0.1:8888 --http-alias=localhost:8888
    hostname: vectrum_node
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - vectrum-node-data-volume:/data
      #- ./data/node:/data
    cap_add:
      - IPC_LOCK
    stop_grace_period: 10m

  vectrum_wallet:
    image: vectrum/vectrum:latest
    command: /opt/vectrum/bin/vectrum-wallet --wallet-dir /data --http-server-address=127.0.0.1:8900 --http-alias=vectrum_wallet:8900 --http-alias=localhost:8900
    hostname: vectrum_wallet
    links:
      - vectrum_node
    volumes:
      - vectrum-wallet-data-volume:/data
      #- ./data/wallet:/data
    stop_grace_period: 10m

volumes:
  vectrum-node-data-volume:
   external: true
  vectrum-wallet-data-volume:
   external: true
